apiVersion: v1
kind: ImageStream
metadata:
  name: custom-grafana
  labels:
    application: custom-grafana
spec:
  tags:
    - name: latest
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: custom-grafana-build
spec:
  source:
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: custom-grafana:latest
