apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tw-na-pipeline-monitor-prometheus
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: tw-na-pipeline-monitor-prometheus
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 0
  desiredReplicas: 0
---
apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'jenkins'
        metrics_path: '/prometheus'
        static_configs:
          - targets: ['jenkins']
kind: ConfigMap
metadata:
  name: prometheus-configmap
