{
 "title": "jenkins metrics collect",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Lead Time (in last 1 day)",
   "type": "stat",
   "description": "just  average value  in one day,  change the range in the query to change the time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(default_jenkins_builds_merge_lead_time[1d])"
    }
   ]
  },
  {
   "title": "Average Recovery Time (in 1 day)",
   "type": "stat",
   "description": "same as the average lead time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(default_jenkins_builds_failed_build_recovery_time[1d])"
    }
   ]
  },
  {
   "title": " Average Failure Rate (in 1 day)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(default_jenkins_builds_failed_build_total_count[1d]) / increase(default_jenkins_builds_build_total_count[1d])"
    }
   ]
  },
  {
   "title": "Deployment Frequency (in last 1 day)",
   "type": "stat",
   "description": "count by total number,  more accurate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time(default_jenkins_builds_build_total_count[1d]) - max_over_time(default_jenkins_builds_build_total_count[1d] offset 1d)"
    }
   ]
  },
  {
   "title": "Deployment Frequency (in last 1 day)(for test)",
   "type": "stat",
   "description": "count by the result ,  apply for no miss and duplicate data. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count_over_time(default_jenkins_builds_last_build_result_code[1d])"
    }
   ]
  }
 ]
}