apiVersion: v1
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
      - name: 'provider name'
        orgId: 1
        folder: ''
        folderUid: ''
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: /etc/grafana/provisioning/dashboards
  datasource.yaml: |
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://tw-na-pipeline-monitor-prometheus:9090
  jenkins-metrics-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 2,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": true,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 7,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 16,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": false,
            "total": false,
            "values": false
          },
          "lines": false,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "(hour(default_jenkins_builds_last_build_start_timestamp{jenkins_job=\"metrics-dev/metrics-dev-sample-pipeline\",result=~\".*\"}/1000)+8)",
              "format": "time_series",
              "instant": false,
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Start Time Distribution",
          "tooltip": {
            "shared": false,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": 24,
            "max": 23,
            "min": 0,
            "mode": "histogram",
            "name": null,
            "show": true,
            "values": [
              "total"
            ]
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "decimals": null,
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "datasource": "Prometheus",
          "description": "same as the average lead time",
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 10,
          "options": {
            "colorMode": "value",
            "fieldOptions": {
              "calcs": [
                "last"
              ],
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                },
                "unit": "ms"
              },
              "overrides": [],
              "values": false
            },
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto"
          },
          "pluginVersion": "6.7.0-beta1",
          "targets": [
            {
              "expr": "avg_over_time(default_jenkins_builds_failed_build_recovery_time[1d])",
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Average Recovery Time (in last 1 day)",
          "type": "stat"
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Prometheus",
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 7
          },
          "hiddenSeries": false,
          "id": 14,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "dataLinks": []
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "count_over_time(default_jenkins_builds_last_build_duration_in_milliseconds{jenkins_job=\"metrics-dev/metrics-dev-sample-pipeline\",result=~\".*\"}[1d])",
              "interval": "",
              "legendFormat": "{{result}}-triggerBy={{triggeredBy}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Triggered By",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "cacheTimeout": null,
          "datasource": "Prometheus",
          "description": "count by total number,  more accurate.",
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          },
          "id": 4,
          "links": [],
          "options": {
            "colorMode": "value",
            "fieldOptions": {
              "calcs": [
                "last"
              ],
              "defaults": {
                "links": [],
                "mappings": [],
                "nullValueMode": "connected",
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                },
                "title": "",
                "unit": "none"
              },
              "overrides": [],
              "values": false
            },
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "horizontal"
          },
          "pluginVersion": "6.7.0-beta1",
          "targets": [
            {
              "expr": "sum(count_over_time(default_jenkins_builds_last_build_duration_in_milliseconds{jenkins_job=\"metrics-dev/metrics-dev-sample-pipeline\"}[1d]))",
              "interval": "",
              "legendFormat": "",
              "refId": "B"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Deployment Frequency (in last 1 day)",
          "type": "stat"
        },
        {
          "datasource": "Prometheus",
          "description": "just  average value  in one day,  change the range in the query to change the time",
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 15
          },
          "id": 12,
          "options": {
            "colorMode": "value",
            "fieldOptions": {
              "calcs": [
                "last"
              ],
              "defaults": {
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                },
                "unit": "ms"
              },
              "overrides": [],
              "values": false
            },
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto"
          },
          "pluginVersion": "6.7.0-beta1",
          "targets": [
            {
              "expr": "avg_over_time(default_jenkins_builds_merge_lead_time{triggeredBy=\"developer-admin-edit-view\"}[1d])",
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Average Lead Time (in last 1 day)",
          "type": "stat"
        },
        {
          "datasource": "Prometheus",
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 23
          },
          "id": 6,
          "options": {
            "colorMode": "value",
            "fieldOptions": {
              "calcs": [
                "last"
              ],
              "defaults": {
                "links": [],
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                }
              },
              "overrides": [],
              "values": false
            },
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto"
          },
          "pluginVersion": "6.7.0-beta1",
          "targets": [
            {
              "expr": "sum(count_over_time(default_jenkins_builds_last_build_duration_in_milliseconds{jenkins_job=\"metrics-dev/metrics-dev-sample-pipeline\",result=\"FAILURE\"}[1d]))/sum(count_over_time(default_jenkins_builds_last_build_duration_in_milliseconds{jenkins_job=\"metrics-dev/metrics-dev-sample-pipeline\"}[1d]))",
              "hide": false,
              "interval": "",
              "legendFormat": "",
              "refId": "B"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": " Average Failure Rate (in last 1 day)",
          "type": "stat"
        }
      ],
      "refresh": "10s",
      "schemaVersion": 22,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-3h",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "",
      "title": "jenkins metrics collect2",
      "uid": "hEXGaUuZk3",
      "variables": {
        "list": []
      },
      "version": 2
    }
kind: ConfigMap
metadata:
  name: grafana-configmap
